version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - mysql
    volumes:
      - .:${PAYUM_ROOT_DIR}
      - ${PAYUM_ROOT_DIR}/app/cache
      - ${PAYUM_ROOT_DIR}/app/logs
    environment:
      - PAYUM_ROOT_DIR=${PAYUM_ROOT_DIR}
      - SYMFONY__ENV_DATABASE_HOST=mysql
      - SYMFONY__ENV_DATABASE_PORT=3306
      - SYMFONY__ENV_DATABASE_NAME=payum
      - SYMFONY__ENV_DATABASE_USER=root
      - SYMFONY__ENV_DATABASE_PASSWORD=rootpass
      - SYMFONY__ENV_MONGODB_HOST=mongodb
      - SYMFONY__ENV_MONGODB_PORT=27017
      - SYMFONY__ENV_MONGODB_NAME=payum

  mysql:
    image: mariadb:10
    ports:
      - "3306:3306"
    volumes:
      - ./docker/container/mysql:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass

  mongodb:
    image: mongo:3.0.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mysql-data:
    driver: local
  mongo-data:
    driver: local